   repos:
     - repo: local
       hooks:
         - id: autoflake
           name: autoflake
           entry: autoflake --recursive --in-place --remove-unused-variables --remove-imports .
           language: system
           pass_filenames: false
           types: [python]
         - id: black
           name: black
           entry: black .
           language: system
           pass_filenames: false
           types: [python]
