apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: microservice
build:
  artifacts:
  - image: micro-interface
    context: .
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: './*.py'
          src: '.'
  local:
    push: false