apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: react-gui
build:
  artifacts:
  - image: react-gui-image
    context: .
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: '*.js'
          src: '.'
  local:
    push: false